### ISSUE TITLE
Problems opening Matplotlib code on Github.

### ISSUE THREAD

**Issue by carlisavannah** [carlisavannah/astr-119-session-6#1]
I'm having some trouble opening my files from jupyter.  I was hoping you could help? @adwasser

**Comment by adwasser** [comment]
@carlisavannah, I can view the notebook fine when downloading it.  I've heard from a few others who noticed that GitHub is having trouble rendering ipynb files.  It's inconvenient, but not a problem.

**Comment by carlisavannah** [comment]
This issue has been addressed.
